apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: #{imageRESULT}#
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          requests:
            cpu: "100m"  # Establece la solicitud de CPU
          limits:
            cpu: "200m"  # Establece el límite máximo de CPU
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: result-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80